### ISSUE TITLE
Debugging connection issues

### ISSUE THREAD

**Issue by dhirschfeld** [jupyterhub/ldapauthenticator#116]
It can be useful to use the underlying `ldap3` library to ensure the configuration is correct. This can be done as shown below:
```python
server = ldap3.Server(server_address, port=389, use_ssl=False)
conn = ldap3.Connection(server, user=lookup_dn_search_user, password=lookup_dn_search_password, auto_bind=ldap3.AUTO_BIND_NO_TLS)
is_bound = conn.bind()
assert is_bound
conn.search(
    search_base=user_search_base,
    search_scope=ldap3.SUBTREE,
    search_filter='(sAMAccountName=dhirschfeld)',
    attributes=ldap3.ALL_ATTRIBUTES
)
conn.response[0]
resp = conn.response[0]
print(resp['attributes'][lookup_dn_user_dn_attribute])
```

**Comment by Cronan** [comment]
How does the above code map to the config?

The following works with my server:

```python
import ldap3
server = ldap3.Server("my-ldap.ad.server.com", port=389, use_ssl=False)
conn = ldap3.Connection(server, user="my_ldap@ad.server.com", password="super_secret", auto_bind=ldap3.AUTO_BIND_NO_TLS)
is_bound=conn.bind()
conn.search(search_base="DC=ad,DC=server,DC=com", search_scope=ldap3.SUBTREE,search_filter='(sAMAccountName=bbloggs)',attributes=ldap3.ALL_ATTRIBUTES)
resp = conn.response[0]
print(resp['attributes']['cn'])
Blogs, Bill
print(resp['attributes']['uid'])
bblogs
```

My jupyterhub config is as follows:

```yml
auth:
  type: ldap
  ldap:
    server:
      address: my-ldap.ad.server.com:389
    dn:
      lookup: true
      search:
        filter: '({login_attr}={login})'
        user: 'my_ldap@ad.server.com'
        password: 'super_secret'
      user:
        searchBase: 'DC=ad,DC=server,DC=com'
        escape: False
        attribute: 'sAMAccountName'
        dnAttribute: 'cn'
```

I still get the following error:
`ldapauthenticator:379] Invalid password for user bbloggs`
