### ISSUE TITLE
Users restriction as allowed_groups is not working

### ISSUE THREAD

**Issue by kadafax** [jupyterhub/ldapauthenticator#145]
Hi,

Using a freshly installed "the-littlest-jupyterhub" and this plugin, I am able to log against my LDAP (openldap) but can't discriminate users based on their membership of a group because in my directory the users are added to a group with the attribute memberUID and it's not working with this plugin who is searching for other attributes.

So my question is, how can I discriminate users based on another attribute in their LDAP account. I'm thinking of narrowing the user search with a filter like (&(uid=username)(someAttribute=jupyter)) but can't figure how to achieve this.

Thanks for any help. Below my config.yaml:

```
users:
  admin:
  - aLocalUser
  - aLDAPUser
https:
  enabled: true
  tls:
    key: /etc/mycerts/myserver_myOrg_fr.key
    cert: /etc/mycerts/myserver_myOrg_fr.crt
auth:
  LDAPAuthenticator:
    server_address: my.ldap.server
    bind_dn_template: uid={username},ou=people,dc=myOrg,dc=org
    use_ssl: true
    server_port: 636
  type: ldapauthenticator.LDAPAuthenticator
```
