### ISSUE TITLE
Failed Login 

### ISSUE THREAD

**Issue by sorin00** [jupyterhub/ldapauthenticator#152]
Hello,
Currently having issues configuring the authenticator. 
It seems to work for some users but for some not.
I am receiving the Failed Login for  xxxx (See below for logs).

```
[I 2020-01-05 13:05:00.317 JupyterHub log:174] 200 GET /hub/health (@10.96.107.206) 1.71ms
[W 2020-01-05 13:05:00.925 JupyterHub ldapauthenticator:379] Invalid password for user sorin.ispas
[W 2020-01-05 13:05:00.925 JupyterHub base:714] Failed login for sorin.ispas
[I 2020-01-05 13:05:00.927 JupyterHub log:174] 200 POST /hub/login?next= (@10.96.32.62) 327.29ms
```

the configuration is:
```yaml
auth:
  type: ldap
  ldap:
    server:
      address: ldaps://ldap.yyy.local:636
    dn:
      lookup: true
      search:
        filter: '({login_attr}={login})'
        user: 'ldap.jupyter@yyy.local'
        password: 'XXXXXXXX'
      templates:
        - '{username}'
      user:
        searchBase: 'OU=yyy,DC=yyy,DC=local'
        escape: True
        attribute: 'sAMAccountName'
        dnAttribute: 'cn'
```

Can you help me ?

thanks
Sorin
