### ISSUE TITLE
ldap3.core.exceptions.LDAPStartTLSError

### ISSUE THREAD

**Issue by sebastian-luna-valero** [jupyterhub/ldapauthenticator#194]
### Bug description

LDAP authentication works just fine with JupyterHub version 0.9.x and this configuration:
```
auth:
  type: ldap
  ldap:
    server:
      address: ldap.example.org
    dn:
      templates:
        - 'uid={username},ou=People,dc=example,dc=org'
```
However, I found that versions 0.10+ of JupyterHub produce the following error in the hub’s pod:
```
ldap3.core.exceptions.LDAPStartTLSError: ('wrap socket error: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1123)',)
```
with the equivalent LDAP configuration
```
hub:
  config:
    JupyterHub:
      authenticator_class: ldapauthenticator.LDAPAuthenticator
    LDAPAuthenticator:
      bind_dn_template:
        - uid={username},ou=People,dc=example,dc=org
      server_address: ldap.example.org
``` 

#### Expected behaviour

Our LDAP server hasn't changed so we would expect `ldapauthenticator` version 1.3.2 to work like version 1.3.0.

#### Actual behaviour

LDAP authentication with `ldapauthenticator` version 1.3.2 shouldn't produce the exception above.

### How to reproduce

1. Configure `values.yaml` with LDAP authentication
2. Deploy JupyterHub version 0.10 or above
3. Try to login to JupyterHub after deployment
4. See error with `kubectl logs pod/hub-69fdcf79b7-xr946 | grep -i ldap`

### Your personal set up

 - OS:
Kubernetes cluster deployed with Magnum on OpenStack Train
OS: fedora-coreos-32.20200629.3.0

 - Version(s):
JupyterHub 0.9 installs `ldapauthenticator` version 1.3.0
JupyterHub 0.10 installs `ldapauthenticator` version 1.3.2
JupyterHub 0.11 installs `ldapauthenticator` version 1.3.2

I am always using `zero-to-jupyterhub` deployment.

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/ldap3-core-exceptions-ldapstarttlserror/7935/3

**Comment by 1kastner** [comment]
@sebastian-luna-valero could you also report the installed versions of the ldap3 module for each JupyterHub version?

**Comment by sebastian-luna-valero** [comment]
@1kastner sorry, could you please provide steps to get that info?

**Comment by 1kastner** [comment]
@sebastian-luna-valero You need to launch the very same Python the JupyterHub is running with. Then you can simply import the library and check its version number. Just the first google hit: https://stackoverflow.com/questions/20180543/how-to-check-version-of-python-modules

**Comment by sebastian-luna-valero** [comment]
Thanks. I am deploying JupyterHub on kubernetes, how can I check it in that case?

**Comment by 1kastner** [comment]
Please check that yourself, I have no access to a kubernetes setup.

**Comment by sebastian-luna-valero** [comment]
Hi,

I think these are the answers:
* JupyterHub 0.9.1 ships ldap3 version 2.7
* JupyterHub 0.10.6 ships ldap3 version 2.8.1
* JupyterHub 0.11.1 ships ldap3 version 2.8.1

For future reference, here are the commands to check:
```
# log into the hub pod
kubectl exec -it pod/hub-69fdcf79b7-xr946 /bin/bash

# check ldap3 version
cat /usr/local/lib/python3.8/dist-packages/ldap3/version.py
```

I hope that helps.

Best regards,
Sebastian

**Comment by 1kastner** [comment]
Maybe you can have a look at https://github.com/jupyterhub/ldapauthenticator/issues/186 which looks very similar. Check whether your ldap server uses SSL or START_TLS. Maybe you can just play with `use_ssl: true`?

**Comment by sebastian-luna-valero** [comment]
Hi,

Our LDAP server uses START_TLS and when I add `use_ssl:true` with `JupyterHub-0.11.1`, `ldapauthenticator-1.3.2`, `ldap3-2.8.1`:
```
hub:
  config:
    JupyterHub:
      authenticator_class: ldapauthenticator.LDAPAuthenticator
    LDAPAuthenticator:
      bind_dn_template:
        - uid={username},ou=People,dc=example,dc=org
      server_address: ldap.example.org #or ldaps://ldap.example.org
      use_ssl: true
```
I get:
```
ldap3.core.exceptions.LDAPSocketOpenError: socket connection error while opening: [Errno 111] Connection refused
```
On the other hand, adding `use_ssl: true` to the JupyterHub 0.10.6 configuration seems to have no effect so it returns:
```
ldap3.core.exceptions.LDAPStartTLSError: ('wrap socket error: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1123)',)
```
Best regards,
Sebastian
