### ISSUE TITLE
Add end to end test to ensure compatibility against various jupyterhub versions

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/ldapauthenticator#222]
There is a test suite setup, but its not involving jupyterhub.

### Notes on doing this

Below are some pieces of code relevant to include when setting up the test environment to test against various versions of jupyterhub taken from [systemdspawner](https://github.com/jupyterhub/systemdspawner/blob/v1.0.0/.github/workflows/test.yaml#L30)

```yaml
    strategy:
      fail-fast: false
      matrix:
        include:
          # oldest supported python and jupyterhub version
          - python-version: "3.8"
            pip-install-spec: "jupyterhub==2.3.0 tornado==5.1.0 sqlalchemy==1.*"
          - python-version: "3.9"
            pip-install-spec: "jupyterhub==2.* sqlalchemy==1.*"
          - python-version: "3.10"
            pip-install-spec: "jupyterhub==3.*"
          - python-version: "3.11"
            pip-install-spec: "jupyterhub==4.*"

    steps:
      # ...
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install Node dependencies
        run: |
          npm install -g configurable-http-proxy

      - name: Install Python dependencies
        run: |
          pip install ${{ matrix.pip-install-spec }}
```
